### ISSUE TITLE
scew converts XML_Char to char*

### ISSUE THREAD

**Issue by tawmoto** [aconchillo/scew#2] opened 2019-07-30 15:46 UTC
https://github.com/aconchillo/scew/blob/master/scew/parser.c#L288

On Windows, XML_Char is a wchar_t and you convert it to a char* which fails for UNICODE characters.

**Comment by aconchillo** [comment] 2019-08-02 18:02
Changing a pointer type shouldn't mess up the data. That's the pointer type expected by `XML_Parse`. In Windows, you have to make sure you use one of these two configurations: `Release UTF-16` or `Debug UTF-16` (if you use Visual Studio) and that you link with the right generated SCEW library files. See https://github.com/aconchillo/scew/blob/master/win32/README.txt for more details.

Please, let me know what steps you followed, what compiler, defines or any other data that might help diagnose your issue.

**Comment by tawmoto** [comment] 2019-08-02 18:06
Thanks, we upgraded from scew 0.x in which everything was char from what I remember and now it crashed. We managed to fix it with some hacks in expat header than scew includes.
We are not using vstudio, but cmake.
Thanks again

**Comment by tawmoto** [comment] 2019-08-02 18:08
In the past we used all char , in 0.x, we are using a multiplatform environment, but when wchar appeared in scew...it broke compatibility I think...

**Comment by aconchillo** [comment] 2019-08-02 18:25
Are you using UTF-16? Because that's only supported in Windows. But SCEW should handle well UTF-8 in both Linux, OS X or Windows platforms.

**Comment by aconchillo** [comment] 2019-08-02 18:27
Closing the issue for now. If you have steps to reproduce the crash I would be happy to help. Please, feel free to reopen the issue if so.

**Closed as completed by aconchillo** 2019-08-02 18:27 UTC

**Comment by tawmoto** [comment] 2019-08-02 18:38
Thank you very much for your support
